name: sniffmap workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build Spring Boot project
        run: ./mvnw clean install
        working-directory: backend

#      - name: Run Spring Boot tests
#        run: ./mvnw test
#        working-directory: backend

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build React project
        run: npm run build
        working-directory: frontend

#      - name: Run React tests
#        run: npm test
#        working-directory: frontend
