name: sniffmap backend

on:
  push:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ $(docker ps -q -f name=sniffmap_db) ]; then
            echo "MariaDB container is running."
            else
            echo "MariaDB container is not running."
            docker start sniffmap_db
            fi
            docker exec sniffmap_db mariadb -e "SHOW DATABASES;"
            cd app/SniffMap
            git pull origin main
            ./gradlew build
            java -jar ./build/libs/SniffMap-0.0.1-SNAPSHOT.jar

